# Generated by Django 4.1.5 on 2023-02-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shell", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="shell", old_name="image", new_name="pic",),
    ]
